/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Desktop;
import java.net.URI;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author duong
 */
public class GUI_MainApplication extends javax.swing.JFrame {

    /**
     * Creates new form GUI_MainApplication
     */
    public GUI_MainApplication() {
        initComponents();
        initApp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItem_ViewMyProfile = new javax.swing.JMenuItem();
        menuItem_XemMaNguon = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Thông tin");

        menuItem_ViewMyProfile.setText("Về tác giả");
        menuItem_ViewMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ViewMyProfileActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_ViewMyProfile);

        menuItem_XemMaNguon.setText("Xem mã nguồn mở");
        menuItem_XemMaNguon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_XemMaNguonActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_XemMaNguon);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_XemMaNguonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_XemMaNguonActionPerformed
        // TODO add your handling code here:
        try {       
            URL url = new URL("https://github.com/kennex666/EncryptionAlgorithm-Java");

            openWebpage(url.toURI());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Không thể mở web do thiếu API Desktop, truy cập tại: https://github.com/kennex666/EncryptionAlgorithm-Java ");
        }
    }//GEN-LAST:event_menuItem_XemMaNguonActionPerformed

    private void menuItem_ViewMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ViewMyProfileActionPerformed
        // TODO add your handling code here:
        try {       
            URL url = new URL("https://dtbao.io.vn/?s=JAVA-Encryption-Algorithms");

            openWebpage(url.toURI());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Không thể mở web do thiếu API Desktop, truy cập tại: https://dtbao.io.vn/?s=JAVA-Encryption-Algorithms");
        }
    }//GEN-LAST:event_menuItem_ViewMyProfileActionPerformed

    public static boolean openWebpage(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(uri);
                return true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Không thể mở web do thiếu API Desktop, truy cập tại: https://github.com/kennex666/EncryptionAlgorithm-Java ");
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MainApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MainApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuItem_ViewMyProfile;
    private javax.swing.JMenuItem menuItem_XemMaNguon;
    // End of variables declaration//GEN-END:variables

    private void initApp() {
        Panel_MaHoaCoDien panelMaHoaCoDien = new Panel_MaHoaCoDien();

        jTabbedPane1.add(panelMaHoaCoDien, "Mã hoá cổ điển");
        this.setTitle("Các thuật toán mã hoá | (c) Dương Thái Bảo - DHKTPM17B - FIT@IUH");

    }
}
